-   id: dbt-core-check
    name: Check for dbt-core usage
    description: This hook verifies that dbt-core functionality is not being used in an adapter.
    entry: dbt-core-check
    language: system
    types: [python]
